export enum Backgrounds {
    YURTA = "bg_yurta",
    BLACK = "bg_black",
    FALCON_DREAM = "bg_eagle_space",
    BALBAL = "bg_balbal",
    HORSES = "bg_horses",
    YURTA_OUTSIDE = "bg_yurta_outside",
    WHITE = "bg_white",
    SPY_ATTACK = "bg_spy_attack",
    STEPPE_ARMY = "bg_steppe_army",
    YURTA_NIGHT = "bg_yurta_night",
    KANYKEI_ROOM = "bg_kanykei_room",
    OATH_HILL = "bg_oath_hill",
    BEIJING_WALLS = "bg_beijing_walls",
    ALMAMBET_CAMP = "bg_almambet_camp",
    CHUBAK_CAMP = "bg_chubak_camp",
    BATTLE_CHAOS = "bg_battle_chaos",
    FINAL_PRAYER = "bg_final_prayer",
}

export enum Emotions {
    STORYTELLER_BASE = "storyteller_base",
    JAKYP_SAD = "jakyp_sad",
    JAKYP_HOPE = "jakyp_hope",
    CHIYIRDI_SHOCK = "chiyirdi_shock",
    SPY_ATTACK = "spy_attack",
    MANAS_NEON_EYES = "manas_neon_eyes",
    MANAS_ADULT = "manas_adult",
    BAKAI_BASE = "bakai_base",
    ALMAMBET_BASE = "almambet_base",
    KANYKEI_BASE = "kanykei_base",
    CHUBAK_BASE = "chubak_base",
    KONURBAY_BASE = "konurbay_base",
}
